#!/bin/bash

image_prefix=~/.swaylock.
image_ext=".jpg"

outputs="$(swaymsg -rt get_outputs | jq '.[].name' -r)"

function get_images_arg {
  echo "$outputs" | while read output; do
    echo -n "-i $output:${image_prefix}${output}${image_ext} "
  done
}

images_arg="$(get_images_arg)"

echo "$outputs" | parallel \
  "grim -t jpeg -q 97 -o {} '${image_prefix}{}${image_ext}';" \
  "convert '${image_prefix}{}${image_ext}' -filter Gaussian -resize 12.5% -define filter:sigma=2.5 -resize 800% ~/Pictures/Wallpapers/eidoslock.png -gravity center -composite '${image_prefix}{}${image_ext}'"

swaylock $images_arg $@

sleep 0.5

echo "$outputs" | while read output; do
  rm "${image_prefix}${output}${image_ext}"
done
