#!/bin/bash

# Show usage on --help
if [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "" ]; then
  echo "Usage: $0 [dev] [up|down]"
  exit 0
fi

# Get and validate action
if [ "$2" == "up" ]; then
  offset="5%+"
elif [ "$2" == "down" ]; then
  offset="5%-"
else
  exit 1
fi


# Set brightness
new_br="$(brightnessctl -m -d $1 set $offset | awk -F ',' '{ print $4 }' )"

# Send notification

# Retrieve notification id
notif_id_arg="-r $(cat /tmp/.swaybrightness-nid 2> /dev/null)"
if [ "$notif_id_arg" == "-r " ]; then
  notif_id_arg="-p"
fi

# Set emoji
emoji="🔆"

notify-send -p $notif_id_arg -t 1000 "$emoji Brightness" "Brightness ${new_br}" > /tmp/.swaybrightness-nid

