#!/bin/bash

image_prefix=~/.swaylock.
image_ext=".jpg"

outputs="$(swaymsg -rt get_outputs | jq '.[].name' -r)"

function get_images_arg {
  echo "$outputs" | while read output; do
    echo -n "-i $output:${image_prefix}${output}${image_ext} "
  done
}

images_arg="$(get_images_arg)"

echo "$outputs" | parallel \
  "grim -t jpeg -q 40 -o {} '${image_prefix}{}${image_ext}';" \
  "blur_image -r 97 '${image_prefix}{}${image_ext}' -o '${image_prefix}{}${image_ext}'"

swaylock $images_arg $@

sleep 0.5

echo "$outputs" | while read output; do
  rm "${image_prefix}${output}${image_ext}"
done
